/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fri.zoznamstudentov;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author janik
 */
public class OknoSoZoznamom extends javax.swing.JFrame {

    private final DefaultListModel<Student> zoznamStudentov;

    /**
     * Creates new form OknoSoZoznamom
     */
    public OknoSoZoznamom() {
        this.zoznamStudentov = new DefaultListModel<Student>();
        
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        lstZoznamStudentov = new javax.swing.JList<>();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        txtMeno = new javax.swing.JTextField();
        txtPriezvisko = new javax.swing.JTextField();
        btnVloz = new javax.swing.JButton();
        btnOprav = new javax.swing.JButton();
        btnVymaz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        lstZoznamStudentov.setModel(this.zoznamStudentov);
        lstZoznamStudentov.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstZoznamStudentovValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstZoznamStudentov);

        getContentPane().add(jScrollPane1);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        txtMeno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentFocusLost(evt);
            }
        });
        jPanel1.add(txtMeno);

        txtPriezvisko.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentFocusLost(evt);
            }
        });
        jPanel1.add(txtPriezvisko);

        btnVloz.setText("Vlož");
        btnVloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVlozActionPerformed(evt);
            }
        });
        jPanel1.add(btnVloz);

        btnOprav.setText("Oprav");
        btnOprav.setEnabled(false);
        jPanel1.add(btnOprav);

        btnVymaz.setText("Vymaž");
        btnVymaz.setEnabled(false);
        jPanel1.add(btnVymaz);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVlozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVlozActionPerformed
        if (this.txtMeno.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Nezadal si meno");
            this.txtMeno.grabFocus();
            return;
        }
        if (this.txtPriezvisko.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Nezadal si priezvisko");
            this.txtPriezvisko.grabFocus();
            return;
        }
        Student novyStudent = new Student(this.txtMeno.getText(), this.txtPriezvisko.getText());
        this.zoznamStudentov.addElement(novyStudent);
        this.txtMeno.setText("");
        this.txtPriezvisko.setText("");
        this.txtMeno.grabFocus();
    }//GEN-LAST:event_btnVlozActionPerformed

    private void studentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentFocusGained
        this.getRootPane().setDefaultButton(this.btnVloz);
    }//GEN-LAST:event_studentFocusGained

    private void studentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentFocusLost
        this.getRootPane().setDefaultButton(null);
    }//GEN-LAST:event_studentFocusLost

    private void lstZoznamStudentovValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstZoznamStudentovValueChanged
        if (this.lstZoznamStudentov.getSelectedIndex() == -1) {
            this.btnOprav.setEnabled(false);
            this.btnVymaz.setEnabled(false);
        } else {
            this.btnOprav.setEnabled(true);
            this.btnVymaz.setEnabled(true);
        }
    }//GEN-LAST:event_lstZoznamStudentovValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOprav;
    private javax.swing.JButton btnVloz;
    private javax.swing.JButton btnVymaz;
    private javax.swing.JList<Student> lstZoznamStudentov;
    private javax.swing.JTextField txtMeno;
    private javax.swing.JTextField txtPriezvisko;
    // End of variables declaration//GEN-END:variables
}
